# docker-compose.yml
version: "3"
services:
  springappserver:
    build: .
    depends_on:
      - mysql
    networks:
      - mt-network
    ports:
      - ${SPRING_API_PORT}:8080
    volumes:
      - .:/data/spring-boot-app
    environment:
      SPRING_ENVIRONMENT: ${SPRING_ENVIRONMENT}
      SPRING_DB_URL: ${SPRING_DB_URL}
      SPRING_DB_SCHEMA: ${SPRING_DB_SCHEMA}
      SPRING_DB_USER: ${SPRING_DB_USER}
      SPRING_DB_PASSWORD: ${SPRING_DB_PASSWORD}
      WAIT_HOSTS: mysql:3306

  mysql:
    image: mysql:8
    networks:
      - mt-network
    environment:
      MYSQL_DATABASE: ${SPRING_DB_SCHEMA}
      MYSQL_USER: ${SPRING_DB_USER}
      MYSQL_PASSWORD: ${SPRING_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SPRING_DB_PASSWORD}
    volumes:
      - /data/mysql
    ports:
      - 13306:3306

networks:
  mt-network:
    driver: bridge