logging:
  config: ./src/main/resources/logback-prod.xml
  level:
    org.springframework: ERROR
    id.lmnzr.geometry.demo: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log
